### ISSUE TITLE
Poetry not found in puya project

### ISSUE THREAD

**Issue by lollobene** [algorandfoundation/algokit-cli#420]
I tried to create a puya project from algokit cli, but I get an error when trying to bootstrap:

Poetry not found; attempting to install it...
? We couldn't find `poetry`; can we install it for you via pipx so we can install Python dependencies? Yes
Installing Python dependencies and setting up Python virtual environment via Poetry
Error: Unable to access Poetry on PATH after installing it via pipx; check pipx installations are on your path by running `pipx ensurepath` and try `algokit bootstrap poetry` again.

I tried everything, like reinstalling python/pipx, both via brew or Python binaries. Seems like the problem is still there.

This is the output of `algokit doctor`:

timestamp: 2024-02-16T18:16:22+00:00
AlgoKit: 1.11.3
AlgoKit Python: 3.12.2 (main, Feb  6 2024, 20:19:44) [Clang 15.0.0 (clang-1500.1.0.2.5)] (location: /Users/lollobene/.local/pipx/venvs/algokit)
OS: macOS-14.2.1-arm64-arm-64bit
docker: 25.0.3
docker compose: 2.24.5-desktop.1
git: 2.39.3
python: Command not found!
python3: 3.12.2 (location: /Library/Frameworks/Python.framework/Versions/3.12/bin/python3)
pipx: 1.4.3
poetry: Command not found!
  Poetry is required for some Python-based templates;
  install via `algokit bootstrap` within project directory, or via:
  https://python-poetry.org/docs/#installation
node: 20.9.0
npm: 10.2.4
brew: 4.2.8

**Comment by neilcampbell** [comment]
Weird! The doctor output suggests that for some reason poetry isn't available on the path. Everything else looks ok to me.

Are you able to re-run the following and paste the output of each step?
1. `pipx ensurepath`
2. `pipx install poetry --force`
3. Restart your terminal
4. `algokit doctor` and see if poetry can now be found?

**Comment by lollobene** [comment]
1. `pipx ensurepath` gives the following output: 

  `/Users/lollobene/.local/bin is already in PATH.

  ⚠️  All pipx binary directories have been added to PATH. If you are sure you want to proceed, try again with the '--force' flag.

  Otherwise pipx is ready to go! ✨ 🌟 ✨`
  
  2. `pipx install poetry --force` gives the following output:
  
    Installing to existing venv 'poetry'

⚠️  Not removing existing venv /Users/lollobene/.local/pipx/venvs/poetry because it was not created in this session
Traceback (most recent call last):
  File "/opt/homebrew/bin/pipx", line 8, in <module>
    sys.exit(cli())
             ^^^^^
  File "/opt/homebrew/Cellar/pipx/1.4.3/libexec/lib/python3.12/site-packages/pipx/main.py", line 921, in cli
    return run_pipx_command(parsed_pipx_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/pipx/1.4.3/libexec/lib/python3.12/site-packages/pipx/main.py", line 219, in run_pipx_command
    return commands.install(
           ^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/pipx/1.4.3/libexec/lib/python3.12/site-packages/pipx/commands/install.py", line 87, in install
    venv.create_venv(venv_args, pip_args, override_shared)
  File "/opt/homebrew/Cellar/pipx/1.4.3/libexec/lib/python3.12/site-packages/pipx/venv.py", line 165, in create_venv
    pipx_pth = get_site_packages(self.python_path) / PIPX_SHARED_PTH
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/pipx/1.4.3/libexec/lib/python3.12/site-packages/pipx/util.py", line 126, in get_site_packages
    output = run_subprocess(
             ^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/pipx/1.4.3/libexec/lib/python3.12/site-packages/pipx/util.py", line 179, in run_subprocess
    completed_process = subprocess.run(
                        ^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.12/3.12.2_1/Frameworks/Python.framework/Versions/3.12/lib/python3.12/subprocess.py", line 548, in run
    with Popen(*popenargs, **kwargs) as process:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.12/3.12.2_1/Frameworks/Python.framework/Versions/3.12/lib/python3.12/subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/opt/homebrew/Cellar/python@3.12/3.12.2_1/Frameworks/Python.framework/Versions/3.12/lib/python3.12/subprocess.py", line 1953, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/Users/lollobene/.local/pipx/venvs/poetry/bin/python'

3. DONE

4. `algokit doctor` output:

timestamp: 2024-03-11T15:37:29+00:00
AlgoKit: 1.12.3
AlgoKit Python: 3.12.2 (main, Feb  6 2024, 20:19:44) [Clang 15.0.0 (clang-1500.1.0.2.5)] (location: /Users/lollobene/.local/pipx/venvs/algokit)
OS: macOS-14.2.1-arm64-arm-64bit
docker: 25.0.3
docker compose: 2.24.5-desktop.1
git: 2.39.3
python: Command not found!
python3: 3.12.2 (location: /Library/Frameworks/Python.framework/Versions/3.12/bin/python3)
pipx: 1.4.3
poetry: Command not found!
  Poetry is required for some Python-based templates;
  install via `algokit bootstrap` within project directory, or via:
  https://python-poetry.org/docs/#installation
node: 20.9.0
npm: 10.2.4
brew: 4.2.11

If you are experiencing a problem with AlgoKit, feel free to submit an issue via:
https://github.com/algorandfoundation/algokit-cli/issues/new
Please include this output, if you want to populate this message in your clipboard, run `algokit doctor -c`

**Comment by lollobene** [comment]
I solved it by re-installing poetry
