### ISSUE TITLE
KMD Client server 502 Bad Gateway error

### ISSUE THREAD

**Issue by nickthelegend** [algorandfoundation/algokit-cli#587]
### KMD client 502 Bad gateway error

kmd client gives 502 bad gateway error
### Steps to reproduce

1. When i run the test cases using npm run test i get errors
`
● HelloWorld › hello

    SyntaxError: Unexpected token '<', "<html>
    <h"... is not valid JSON
        at JSON.parse (<anonymous>)

      at Function.parseJSON (node_modules/algosdk/src/client/client.ts:125:29)
      at Function.prepareResponse (node_modules/algosdk/src/client/client.ts:186:25)
      at Function.prepareResponseError (node_modules/algosdk/src/client/client.ts:206:33)
      at HTTPClient.get (node_modules/algosdk/src/client/client.ts:247:24)
      at Kmd.listWallets (node_modules/algosdk/src/client/kmd.ts:29:17)
      at KmdAccountManager.getWalletAccount (node_modules/@algorandfoundation/src/types/kmd-account-manager.ts:70:29)
      at KmdAccountManager.getLocalNetDispenserAccount (node_modules/@algorandfoundation/src/types/kmd-account-manager.ts:192:23)
      at AccountManager.localNetDispenser (node_modules/@algorandfoundation/src/types/account-manager.ts:429:23)
      at AccountManager.dispenserFromEnvironment (node_modules/@algorandfoundation/src/types/account-manager.ts:416:9)
      at Object.getTestAccount (node_modules/@algorandfoundation/src/testing/account.ts:50:21)
      at Object.beforeEach (node_modules/@algorandfoundation/src/testing/fixtures/algorand-fixture.ts:94:17)

Test Suites: 1 failed, 1 total     
`
2. When i explored the issue i saw my localhost:4002 which runs my KMD server is giving a 502 Bad Gateway error

i didnt fix my problem still i dont know whats happening with my kmd server 

3. I checked my Docker Containers are running perfectly

in the container algokit_sandbox_proxy  i get this log whever i run my test cases

`
2024-10-27 11:25:29 2024/10/27 07:25:29 [error] 22#22: *45 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: , request: "GET /v1/wallets HTTP/1.1", upstream: "http://172.18.0.4:7833/v1/wallets", host: "localhost:4002"
`

**Comment by nickthelegend** [comment]
i just now fixed this issue which i faced , for other developers out there facing the same issue delete the algokit_sandbox
in the docker desktop 

and run the 

`algokit localnet start`
